language: python
sudo: false

python:
  - "3.5"

install:
  - npm install
  - pip install -r requirements-dev.txt

script:
  - NODE_ENV=production npm run lint
  - NODE_ENV=production npm test
  - invoke test
