language: python
sudo: false

cache:
  directories:
    - node_modules

python:
  - "3.5"

install:
  - cp .env.example .env
  - npm install -g npm@3
  - npm install
  - pip install -r requirements-dev.txt

script:
  - NODE_ENV=production npm run lint
  - NODE_ENV=production npm test
  - invoke test
