api:
  restart: always
  build: .
  dockerfile: Dockerfile-dev
  links:
    - redis
  env_file: .env
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
  volumes:
    - .:/usr/src/app
  expose:
    - "5000"
  command: invoke server --port 5000

redis:
  restart: always
  image: redis:3.0

nginx:
  restart: always
  build: ./compose/nginx
  links:
    - api
  ports:
    - "80:80"
